# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0002_auto_20160514_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='clubNight',
            field=models.CharField(max_length=20),
        ),
    ]
