# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0004_event_fixture_game_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerFile', models.FileField(upload_to='.')),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='rating',
            new_name='grading',
        ),
    ]
