# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0005_auto_20160514_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(default='PENDING', max_length=15),
            preserve_default=False,
        ),
    ]
