# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0006_fixture_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Fixture')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Team')),
            ],
        ),
    ]
