# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0008_fixturefile_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Season'),
        ),
    ]
