# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0009_fixture_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
