# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0011_auto_20160521_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='awayScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='homeScore',
            field=models.IntegerField(null=True),
        ),
    ]
