# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0014_auto_20160528_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Event'),
        ),
    ]
