# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0015_auto_20160528_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='awayTeamID',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='homeTeamID',
        ),
        migrations.AddField(
            model_name='fixture',
            name='awayTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='cdclSite.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='cdclSite.Team'),
        ),
    ]
