# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0016_auto_20160528_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='games',
        ),
        migrations.AddField(
            model_name='fixture',
            name='awaySubmission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awaySubmission', to='cdclSite.Submission'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='homeSubmission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeSubmission', to='cdclSite.Submission'),
        ),
        migrations.AlterField(
            model_name='game',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Submission'),
        ),
    ]
