# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0017_auto_20160529_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Address_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Postcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='backupContactNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='forenames',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='primaryContactNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
