# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdclSite', '0018_auto_20160601_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='fixture',
            new_name='submission',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
