# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0021_remove_userdata_iscaptain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Player'),
        ),
    ]
