# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0023_auto_20160625_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdclSite.Club'),
        ),
    ]
