# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0024_auto_20160626_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clubAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubNight',
            new_name='night',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubVenue',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubWebsite',
            new_name='website',
        ),
    ]
