# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0026_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='blackPlayerID',
            new_name='awayPlayerID',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='blackPlayerScore',
            new_name='awayPlayerScore',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='whitePlayerID',
            new_name='homePlayerID',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='whitePlayerScore',
            new_name='homePlayerScore',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Address_1',
            new_name='aAddress_3',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Address_2',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Address_3',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='Postcode',
            new_name='postcode',
        ),
    ]
