# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0028_auto_20160821_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
