# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0029_auto_20160827_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='postTo',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
