# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0030_announcement_postto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='SiteAnnouncement',
        ),
    ]
