# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0031_auto_20160905_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='address_3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='postcode',
        ),
    ]
