# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0032_auto_20160910_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isCaptain',
            field=models.BooleanField(default=False),
        ),
    ]
