# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdclSite', '0033_player_iscaptain'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
